# Generated by Django 4.2.6 on 2023-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_code',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='Area Code'),
        ),
    ]
