# Generated by Django 4.2.6 on 2023-10-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='area_code',
        ),
    ]
