# Generated by Django 4.2.6 on 2023-10-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_district_area_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='district',
            name='lastupdate',
        ),
        migrations.AddField(
            model_name='district',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.area'),
            preserve_default=False,
        ),
    ]
