# Generated by Django 4.2.6 on 2023-10-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_district_area_district_area_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='district',
            name='lastupdate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last update Time'),
        ),
    ]
