# Generated by Django 4.2.6 on 2023-10-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_district_createdat_district_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.CharField(max_length=8, unique=True, verbose_name='District Code'),
        ),
    ]
